spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gitee?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

logging:
  level:
    com.zhuzb.gitee: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml